services:
  postgres:
    image: postgres:latest
    container_name: postgres_admin
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: admindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: